maps/jail_Hurin_v2.bsp
maps/jail_Hurin_v2.res
models/jail_Hurin/Alus.mdl
models/jail_Hurin/Alus2.mdl
models/jail_Hurin/Alus3.mdl
models/jail_Hurin/Palme.mdl
sound/jail_Hurin/Imperial.wav
sound/jail_Hurin/haha2.wav
sound/jail_Hurin/Hallelujah.wav
gfx/env/mon_sky_bk.tga
gfx/env/mon_sky_dn.tga
gfx/env/mon_sky_ft.tga
gfx/env/mon_sky_lf.tga
gfx/env/mon_sky_rt.tga
gfx/env/mon_sky_up.tga
sound/jail_Hurin/Crowley.wad
sound/jail_Hurin/Vivaldi.wad
models/jail_Hurin/w_mortar.mdl
