maps/jb_satomi.res
gfx/env/desert01bk.tga
gfx/env/desert01dn.tga
gfx/env/desert01ft.tga
gfx/env/desert01lf.tga
gfx/env/desert01rt.tga
gfx/env/desert01up.tga
models/jb_satomi/bush_japan_fern_01.mdl
models/jb_satomi/byka_bush2.mdl
models/jb_satomi/forge_tree1.mdl
models/jb_satomi/jb_bench_plant.mdl
models/jb_satomi/sofa05.mdl
sound/jb_satomi/bell.wav
sound/jb_satomi/death.wav
sound/jb_satomi/forest_amb4.wav
sound/jb_satomi/laser1.wav
sound/jb_satomi/race_go.wav
sound/jb_satomi/teleport_off.wav
sound/jb_satomi/teleport_on.wav
sprites/jb_satomi/laserbeam.spr