gfx/env/jail_russiabk.tga
gfx/env/jail_russiadn.tga
gfx/env/jail_russiaft.tga
gfx/env/jail_russialf.tga
gfx/env/jail_russiart.tga
gfx/env/jail_russiaup.tga
models/niftymaps/jailbreak/dancing_skeleton.mdl
models/niftymaps/jailbreak/hanged_ct.mdl
models/niftymaps/jailbreak/russian_flag.mdl
models/niftymaps/jailbreak/skeleton.mdl
models/niftymaps/jailbreak/tree.mdl
models/niftymaps/jailbreak/vodka.mdl
overviews/jail_russia.bmp
overviews/jail_russia.txt
sound/niftymaps/jailbreak/123_new.wav
sound/niftymaps/jailbreak/ameno.wav
sound/niftymaps/jailbreak/freestyle_battle.wav
sound/niftymaps/jailbreak/jeff.wav
sound/niftymaps/jailbreak/music_1.wav
sound/niftymaps/jailbreak/music_2.wav
sound/niftymaps/jailbreak/music_3.wav
sound/niftymaps/jailbreak/music_4.wav
sound/niftymaps/jailbreak/music_5.wav
sound/niftymaps/jailbreak/music_6.wav
sound/niftymaps/jailbreak/music_6.wav
sound/niftymaps/jailbreak/rps_dead.wav
sound/niftymaps/jailbreak/rrspin.wav
