gfx/env/jb_oasisbk.tga
gfx/env/jb_oasisdn.tga
gfx/env/jb_oasisft.tga
gfx/env/jb_oasislf.tga
gfx/env/jb_oasisrt.tga
gfx/env/jb_oasisup.tga
maps/jb_oasis.res
maps/jb_oasis.txt
models/jb_oasis/bomb.mdl
models/jb_oasis/burger.mdl
models/jb_oasis/grass.mdl
models/jb_oasis/shield.mdl
models/jb_oasis/target.mdl
models/jb_oasis/tree.mdl
overviews/jb_oasis.bmp
overviews/jb_oasis.txt
sound/jb_oasis/123.wav
sound/jb_oasis/bell.wav
sound/jb_oasis/blip.wav
sound/jb_oasis/bomb.wav
sound/jb_oasis/click.wav
sound/jb_oasis/reaction.wav
sound/jb_oasis/shot.wav
sound/jb_oasis/spin.wav
sound/jb_oasis/waterfall.wav
sound/jb_oasis/wind.wav
sprites/jb_oasis/flame.spr
sprites/jb_oasis/laser.spr
sprites/jb_oasis/muzzleflash.spr